# Site settings
description: "A blank repository to use as stub for PHP libraries."
baseurl: "/seed/"
url: "http://fusonic.github.io/seed"
github_username: fusonic
github_repository: seed
version: 1.0.0

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
extensions: [fenced_code_blocks]
sass:
  sass_dir: _sass
  style: :compressed
